name: nexo-jupyter release

on: 
 release:
  types: [published]

jobs:
  build:
    name: nexo-jupyter release
    runs-on: ubuntu-18.04
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      - name: Docker login
        run: echo '${{ secrets.NEXO_DOCKERHUB_ACCESSTOKEN }}' | docker login --username heather999 --password-stdin
      - name: checkout nexo-jupyter
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name : Docker prune
        run: sudo docker system prune && df -h 
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=DOCKTAG::${GITHUB_REF/refs\/tags\//}
      - name: do docker build
        run: docker build --no-cache -t heather999/nexo-jupyter:${{ steps.get_tag.outputs.DOCKTAG }} -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: Docker push tag
        run: docker push heather999/nexo-jupyter:${{ steps.get_tag.outputs.DOCKTAG }}
      - name: tag dev
        run: docker tag heather999/nexo-jupyter:${{ steps.get_tag.outputs.DOCKTAG }} heather999/nexo-jupyter:dev
      - name: Docker push dev
        run: docker push heather999/nexo-jupyter:dev
